language: cpp
compiler:
  - gcc

before_install: sudo apt-get install cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make

matrix:
  include:
    - compiler: gcc
      env: CONFIG=autotools
    - compiler: gcc
      env: CONFIG=cmake
