language: cpp
compiler:
  - gcc

before_install: 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install gcc-4.8 g++-4.8;
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpopt-dev
  - sudo apt-get install cmake
  - sudo g++ --version;  

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make

matrix:
  include:
    - compiler: gcc
      env: CONFIG=cmake
